/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShowroomRouteImport } from './routes/showroom'
import { Route as SellRouteImport } from './routes/sell'
import { Route as MediaRouteImport } from './routes/media'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsSlugRouteImport } from './routes/cars.$slug'
import { Route as BrandsBrandRouteImport } from './routes/brands.$brand'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomRoute = ShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsSlugRoute = CarsSlugRouteImport.update({
  id: '/cars/$slug',
  path: '/cars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandRoute = BrandsBrandRouteImport.update({
  id: '/brands/$brand',
  path: '/brands/$brand',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/inventory': typeof InventoryRoute
  '/media': typeof MediaRoute
  '/sell': typeof SellRoute
  '/showroom': typeof ShowroomRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/cars/$slug': typeof CarsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/inventory': typeof InventoryRoute
  '/media': typeof MediaRoute
  '/sell': typeof SellRoute
  '/showroom': typeof ShowroomRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/cars/$slug': typeof CarsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/inventory': typeof InventoryRoute
  '/media': typeof MediaRoute
  '/sell': typeof SellRoute
  '/showroom': typeof ShowroomRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/cars/$slug': typeof CarsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/inventory'
    | '/media'
    | '/sell'
    | '/showroom'
    | '/sitemap.xml'
    | '/brands/$brand'
    | '/cars/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/inventory'
    | '/media'
    | '/sell'
    | '/showroom'
    | '/sitemap.xml'
    | '/brands/$brand'
    | '/cars/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/inventory'
    | '/media'
    | '/sell'
    | '/showroom'
    | '/sitemap.xml'
    | '/brands/$brand'
    | '/cars/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BlogRoute: typeof BlogRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  InventoryRoute: typeof InventoryRoute
  MediaRoute: typeof MediaRoute
  SellRoute: typeof SellRoute
  ShowroomRoute: typeof ShowroomRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BrandsBrandRoute: typeof BrandsBrandRoute
  CarsSlugRoute: typeof CarsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom': {
      id: '/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof ShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$slug': {
      id: '/cars/$slug'
      path: '/cars/$slug'
      fullPath: '/cars/$slug'
      preLoaderRoute: typeof CarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brand': {
      id: '/brands/$brand'
      path: '/brands/$brand'
      fullPath: '/brands/$brand'
      preLoaderRoute: typeof BrandsBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BlogRoute: BlogRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  InventoryRoute: InventoryRoute,
  MediaRoute: MediaRoute,
  SellRoute: SellRoute,
  ShowroomRoute: ShowroomRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BrandsBrandRoute: BrandsBrandRoute,
  CarsSlugRoute: CarsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
